name       : python-sqlparse
version    : 0.3.0
release    : 2
source     :
    - https://github.com/andialbrecht/sqlparse/archive/0.3.0.tar.gz : a75fddae009fba1d66786203c9dd3a842aa4415475c466d15484139117108474
license    : BSD-3-Clause
component  : programming.python
summary    : A non-validating SQL parser module for Python
description: |
    sqlparse is a non-validating SQL parser for Python. It provides support for parsing, splitting and formatting SQL statements.
build      : |
    %python3_setup
install    : |
    %python3_install
