name       : python-sqlparse
version    : 0.4.1
release    : 3
source     :
    - https://github.com/andialbrecht/sqlparse/archive/0.4.1.tar.gz : f75cdec98a4cc8296890279d744e1ae8618bb14dbad77e3d0637f0d7bb5d6535
license    : BSD-3-Clause
component  : programming.python
summary    : A non-validating SQL parser module for Python
description: |
    sqlparse is a non-validating SQL parser for Python. It provides support for parsing, splitting and formatting SQL statements.
build      : |
    %python3_setup
install    : |
    %python3_install
