name       : python-sqlparse
version    : 0.4.2
release    : 6
source     :
    - https://github.com/andialbrecht/sqlparse/archive/refs/tags/0.4.2.tar.gz : 8108dd2a7b038cc947320ae5d947e8e3d99bb520d81749d3bd419dabcbdf5ed3
license    : BSD-3-Clause
component  : programming.python
summary    : A non-validating SQL parser module for Python
description: |
    sqlparse is a non-validating SQL parser for Python. It provides support for parsing, splitting and formatting SQL statements.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
