name       : python-sqlparse
version    : 0.4.4
release    : 7
source     :
    - https://github.com/andialbrecht/sqlparse/archive/refs/tags/0.4.4.tar.gz : 4cc5b6c4b35190fc741052bf249aa33c5fb8f4c83723aeec87f220bf06bb371a
homepage   : https://github.com/andialbrecht/sqlparse
license    : BSD-3-Clause
component  : programming.python
summary    : A non-validating SQL parser module for Python
description: |
    sqlparse is a non-validating SQL parser for Python. It provides support for parsing, splitting and formatting SQL statements.
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
